# Generated by Django 5.2.4 on 2025-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pc', 'PC'), ('printer', 'Printer'), ('projector', 'Projector'), ('router', 'Router'), ('ups', 'UPS')], max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='working', max_length=20)),
            ],
        ),
    ]
