# Generated by Django 5.2.4 on 2025-07-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
    ]
