# Generated by Django 5.2.4 on 2025-07-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_status_equipment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
    ]
